### ISSUE TITLE
New Candidates to Add

### ISSUE THREAD

**Issue by sr093906** [dreammjow/ChromiumHardening#10]
Latest stable version of Brave disabled following features:

AppDiscoveryRemoteUrlSearch
Prerender2
SpeculationRulesPrefetchProxy
TabGroupsFeedback
WebOTP

**Comment by dreammjow** [comment]
I've already updated my local repo which includes `kPrerender2`, `kAppDiscoveryRemoteUrlSearch`, and everything from `components/optimization_guide/core/optimization_guide_features.cc` disabled. Others don't worth to add.
