### ISSUE TITLE
[Brave Browser] Site that logged in got logged out every browser restart + Broke Settings UI

### ISSUE THREAD

**Issue by SwiftyPop** [dreammjow/ChromiumHardening#13]
After I apply those flags(no command lines applied) , several websites, such as YouTube and Github, are currently logged out every browser restart. That didn't happen before I put those flags in place. 

Disabling `#partitioned-cookies`, `#https-only-mode-setting`, and `#enable-webassembly-lazy-compilation` did not help. I'm guessing flags were the culprit? Wonder what flags is that.

The UI Settings also broke:
![brave_ZTyVts2iNB](https://user-images.githubusercontent.com/90952326/146764124-972fd132-8fe9-4ab6-83dd-e273a64c7212.png)

**Comment by dreammjow** [comment]
Hello @SwiftyPop,

Broke Settings UI is caused by `#webui-branding-update` and make sure `Clear cookies and site data when you close all windows` from `brave://settings/cookies` is disabled.

**Comment by SwiftyPop** [comment]
Thanks that seem to fixed my settings. For cookies, I do put exception for site that I want to logged in like Github or Google's but aight, I'll disable that "clear cookies". Tysm!
