### ISSUE TITLE
[Bug] Flag breaking Twitch.tv when logged in

### ISSUE THREAD

**Issue by Zealest** [dreammjow/ChromiumHardening#5]
I don't know which flag breaks twitch (I followed your flags list on Chromium 94.0.4606.54)
It happens only when you're logged in tho
![Capture](https://user-images.githubusercontent.com/62892019/134772742-8c36cd2a-0f3a-47e3-b736-ff459f6af1a2.PNG)

**Comment by Zealest** [comment]
nevermind I restarted my computer and it works lol

**Comment by Zealest** [comment]
ok nevermind again LMFAO it worked one time then I F5 the window and same error page

**Comment by dreammjow** [comment]
I just signed up on Twitch to test it and nothing had happend yet. Unfortunately, I don't have any solution for it.

Could you update your Chromium build to 94.0.4606.61?

These flags were only added in our list:
```
#brave-debounce
#https-only-mode-setting
#in-product-help-snooze
#partitioned-cookies
#sharing-desktop-screenshots
#sharing-hub-desktop-omnibox
#username-first-flow-fallback-crowdsourcing
```
So, could you set `#https-only-mode-setting` and `#partitioned-cookies` to default/disabled?

**Comment by Zealest** [comment]
Ok, so I updated to 94.0.4606.61 and set `#https-only-mode-setting` and `#partitioned-cookies` to default and the problem persisted.
I don't use any command line flags, only your `chrome://flags` list.
I think I will just stick on stock Chromium and only use the Performance flags
Thanks for your hard work!

**Comment by Zealest** [comment]
Well it's quite weird because the problem persists even with "only" the performance flags and it never happened to me before (I used to follow your entire flags list)
Also, I encoutered this problem only on Twitch so far.

**Comment by dreammjow** [comment]
@Zealest 
The issue is caused by `#enable-webassembly-lazy-compilation`. Set the flag to Default.

Let me know if it is also fixed for you

**Comment by kurtextrem** [comment]
By the way, no issues in latest Chrome Dev.

**Comment by dreammjow** [comment]
@kurtextrem

We disable WebAssembly in our command line flags, which makes this flag placebo, but I kept it, due to most people, who follow the guide (want improved performance), don't use command-line flags.

**Comment by dreammjow** [comment]
https://github.com/brave/brave-browser/issues/18562
This bug will be fixed in Chromium 86+, so let's keep a little reminder here.
