### ISSUE TITLE
[Bug] Breaking Steam, making it only basic HTML Text

### ISSUE THREAD

**Issue by PrincessAkira** [dreammjow/ChromiumHardening#6]

**Comment by PrincessAkira** [comment]
So i found the issue.

#reduce-user-agent is breaking Steam so set it to default

**Comment by PrincessAkira** [comment]
Sites like Stackoverflow and 
https://winscp.net/eng/docs/ui_console
are still borked for example

**Comment by dreammjow** [comment]
I use Steam with `#reduce-user-agent` enabled and I've also tried the other sites that you mentioned and they work fine. If you use Pi-hole, NextDNS or other DNS ad-blocking solutions, please look at blocked requests in Logs.
