### ISSUE TITLE
About QUIC 

### ISSUE THREAD

**Issue by sr093906** [dreammjow/ChromiumHardening#7]
QUIC is recommended for performance consideration but a paper found it is much easier to fingerprint than HTTPS. It may be better to remind users of the issue. 

https://www.theregister.com/2021/01/30/quic_fingerprinting_flaw/

**Comment by dreammjow** [comment]
Disabling it shouldn't be necessary anymore, because `NetworkIsolationKey` already partitions `alt-svc`.
